// .hackerrank/fetch_stats.js
const fs = require("fs");
const https = require("https");

const USERNAME = "vsrajpurohit0666";
const URL = `https://www.hackerrank.com/${USERNAME}`;

// Request options with common browser User-Agent
const options = {
  headers: {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
  }
};

https.get(URL, options, (res) => {
  let html = "";
  res.on("data", (chunk) => (html += chunk));
  res.on("end", () => {
    try {
      // ALWAYS save raw HTML for inspection
      fs.writeFileSync("HACKERRANK_RAW.html", html);

      // Universal hackos extraction (many possible formats)
      let hackos = "Not visible";
      let regex1 = /"hackos"\s*:\s*(\d+)/i;
      let regex2 = /data-analytics=['"][^'"]*"hackos"\s*:\s*(\d+)/i;
      let regex3 = /Hackos:\s*(\d+)/i;
      let regexAny = /hackos["']?\s*[:=]\s*(\d+)/i;

      if (regex1.test(html)) hackos = html.match(regex1)[1];
      else if (regex2.test(html)) hackos = html.match(regex2)[1];
      else if (regex3.test(html)) hackos = html.match(regex3)[1];
      else if (regexAny.test(html)) hackos = html.match(regexAny)[1];
      else {
        // fallback: try to find a likely number near the word "Hackos" within 200 chars
        let idx = html.search(/hackos/i);
        if (idx !== -1) {
          let snippet = html.slice(Math.max(0, idx - 200), idx + 200);
          let nums = snippet.match(/(\d{2,4})/g);
          if (nums && nums.length) hackos = nums[0];
        }
      }

      // Badge detection (try a few patterns)
      let badge = "Not found";
      if (/sql/i.test(html) && /star|★|3-star|3 star/i.test(html)) badge = "SQL (3-Star)";
      else if (/sql/i.test(html)) badge = "SQL (maybe)";

      const output = `
# 🟩 HackerRank — Live Stats (Auto Updated)
🧑‍💻 Username: ${USERNAME}
💰 Hackos: ${hackos}
🏅 Top Badge: ${badge}

⚠ This file was generated by scraping the public profile HTML.
🔎 Raw HTML saved as HACKERRANK_RAW.html for debugging.
`;

      fs.writeFileSync("HACKERRANK_STATS.md", output.trim());
      console.log("Done — raw HTML + stats written.");
    } catch (err) {
      fs.writeFileSync("HACKERRANK_STATS.md", "Error scraping HackerRank: " + String(err));
    }
  });
}).on("error", (e) => {
  fs.writeFileSync("HACKERRANK_STATS.md", "Network error: " + String(e));
});
